@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjMxOGQzM2I0NTg5MmMwZjg1Mzk2NyIsImVtYWlsIjoidGVzdDRAZXhhbXBsZS5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NzEzODc1NCwiZXhwIjoxNzQ3MTQyMzU0fQ.7nOSIzM-q-OPGDyvQqzMkQDlOieu6IPoYkoROOGtd7I

### Registro de usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "test4@example.com",
  "password": "MiContraseña123"
}

### Validar email
POST http://localhost:3000/api/auth/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjMxOGQzM2I0NTg5MmMwZjg1Mzk2NyIsImVtYWlsIjoidGVzdDRAZXhhbXBsZS5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NzEzMDU3OSwiZXhwIjoxNzQ3MTM0MTc5fQ.LtYHPovdLVtF64QrNLWw42FsBJ47C6JatvUUdclJSBc
Content-Type: application/json

{
  "code": "529051"
}

### Login de usuario
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test4@example.com",
  "password": "MiContraseña123"
}

### Onboarding - Datos personales
PUT http://localhost:3000/api/users/onboarding/personal
Authorization: {{ token }}
Content-Type: application/json

{
  "nombre": "Marta",
  "apellidos": "Prieto Rodríguez de Vera",
  "nif": "12345678A"
}

### Onboarding - Datos de compañía
PATCH http://localhost:3000/api/users/onboarding/company
Authorization: {{ token }}
Content-Type: application/json

{
  "nombreEmpresa": "InterWeb S.L.",
  "cif": "B12345678",
  "direccion": "Calle Ejemplo 123, Madrid",
  "telefono": "912345678"
}

### Obtener datos del usuario desde el token
GET http://localhost:3000/api/users/me
Authorization: {{ token }}

### Borrado lógico de usuario
DELETE http://localhost:3000/api/users/me
Authorization: {{ token }}

### Borrado físico de usuario
DELETE http://localhost:3000/api/users/me?soft=false
Authorization: {{ token }}

### FINAL ###

@clientId = 682338de63d335683d87d7ef

### Crear Cliente
POST http://localhost:3000/api/client
Authorization: {{ token }}
Content-Type: application/json

{
  "nombre": "Cliente Ejemplo",
  "email": "cliente@ejemplo.com",
  "telefono": "123456789",
  "direccion": "Calle Falsa 123"
}

### Actualizar Cliente
PUT http://localhost:3000/api/client/{{clientId}}
Authorization: {{ token }}
Content-Type: application/json

{
  "nombre": "Cliente Actualizado",
  "telefono": "987654321"
}

### Listar Todos los Clientes
GET http://localhost:3000/api/client
Authorization: {{ token }}

### Obtener Cliente por ID
GET http://localhost:3000/api/client/{{clientId}}
Authorization: {{ token }}

### Eliminar Cliente (Soft Delete)
DELETE http://localhost:3000/api/client/{{clientId}}
Authorization: {{ token }}

### Eliminar Cliente (Hard Delete)
DELETE http://localhost:3000/api/client/{{clientId}}?hard=true
Authorization: {{ token }}

### Listar Clientes Archivados
GET http://localhost:3000/api/client/archived
Authorization: {{ token }}

### Recuperar Cliente Archivado
PATCH http://localhost:3000/api/client/{{clientId}}/restore
Authorization: {{ token }}

@projectId = 682338f663d335683d87d7f8

### Crear Proyecto
POST http://localhost:3000/api/project
Authorization: {{ token }}
Content-Type: application/json

{
  "nombre": "Proyecto Ejemplo",
  "descripcion": "Este es un proyecto de ejemplo",
  "cliente": "{{ clientId }}"
}

### Actualizar Proyecto
PUT http://localhost:3000/api/project/{{projectId}}
Authorization: {{ token }}
Content-Type: application/json

{
  "nombre": "Proyecto Actualizado",
  "descripcion": "Descripción actualizada del proyecto"
}

### Listar Todos los Proyectos
GET http://localhost:3000/api/project
Authorization: {{ token }}

### Obtener Proyecto por ID
GET http://localhost:3000/api/project/{{projectId}}
Authorization: {{ token }}

### Eliminar Proyecto (Soft Delete)
DELETE http://localhost:3000/api/project/{{projectId}}
Authorization: {{ token }}

### Eliminar Proyecto (Hard Delete)
DELETE http://localhost:3000/api/project/{{projectId}}?hard=true
Authorization: {{ token }}

### Listar Proyectos Archivados
GET http://localhost:3000/api/project/archived
Authorization: {{ token }}

### Restaurar Proyecto Archivado
PATCH http://localhost:3000/api/project/{{projectId}}/restore
Authorization: {{ token }}
